Repository keptn/keptn.github.io, pull requests merged in 2022-03, with the labels that each got.

#1060 Add guidelines and steps for creating a PR
  CONTRIBUTING.md
Labels: contributing, documentation, community

#1079 Fixed broken link to Dynatrace SLI config
  content/docs/0.13.x/quality_gates/sli/index.md
Labels: bug

#1095 docs: Add doc for DCO
  CONTRIBUTING.md
Labels: gsoc

#1110 Fix:fix a typo and refactored MACOS to macOs
  assets/js/libs/doc/misc.js
  content/docs/0.10.x/reference/cli/_index.md
  content/docs/0.11.x/reference/cli/_index.md
  content/docs/0.12.x/reference/cli/_index.md
  content/docs/0.13.x/reference/cli/_index.md
  content/docs/0.14.x/reference/cli/_index.md
  content/docs/0.7.x/reference/cli/_index.md
  content/docs/0.8.x/reference/cli/_index.md
  content/docs/0.9.x/reference/cli/_index.md
  content/docs/quickstart/_index.md
  data/principles.json
Labels: documentation

#1116 docs: Announce Keptn Vulnerability 2022-001
  content/docs/news/vulnerability_bulletins/keptn-sec-2022-001/index.md
Labels: security

#1107 fix: Move reset-git-repos.sh into ./data/config
  content/docs/0.13.x/operate/backup_and_restore/index.md
  content/docs/0.14.x/operate/backup_and_restore/index.md
Labels: bug

#1133 chore: Added a few lines on keeping in sync with the repo
  CONTRIBUTING.md
Labels: contributing

#1136 Add @oleg-nenashev as a reviewer, remove Alois
  .github/CODEOWNERS
Labels: chore

#1135 feat: Add Dependabot
  .github/dependabot.yml
Labels: chore
