Repository keptn/keptn.github.io, pull requests merged in 2022-08, with the labels that each got.

#1331 Create and populate define section
  content/docs/0.18.x/api/_index.md
  content/docs/0.18.x/bridge/_index.md
  content/docs/0.18.x/bridge/manage_projects/index.md
  content/docs/0.18.x/bridge/manage_sequences/index.md
  content/docs/0.18.x/continuous_delivery/_index.md
  content/docs/0.18.x/define/_index.md
  content/docs/0.18.x/define/delivery_assistant/assets/bridge_approval_triggered.png
  content/docs/0.18.x/define/delivery_assistant/assets/bridge_environment_assisteddelivery.png
  content/docs/0.18.x/define/delivery_assistant/index.md
  content/docs/0.18.x/define/delivery_sequence/index.md
  content/docs/0.18.x/define/deployment_helm/index.md
  content/docs/0.18.x/define/quality-gates/index.md
  content/docs/0.18.x/define/remediation-sequence/index.md
  content/docs/0.18.x/define/service/index.md
  content/docs/0.18.x/define/shipyard/index.md
  content/docs/0.18.x/define/triggers/index.md
  content/docs/0.18.x/integrations/_index.md
  content/docs/0.18.x/integrations/how_integrate/index.md
  content/docs/0.18.x/manage/_index.md
  content/docs/0.18.x/manage/update/index.md
  content/docs/0.18.x/quality_gates/_index.md
  content/docs/0.18.x/quality_gates/get_started/index.md
  content/docs/0.18.x/reference/_index.md
  content/docs/0.18.x/reference/files/shipyard/index.md
  content/docs/0.18.x/reference/files/sli/index.md
  content/docs/0.18.x/reference/files/slo/index.md
  content/docs/0.18.x/troubleshooting/index.md
Labels: create-new-project

#1336 How to stop an executing task
  content/docs/0.18.x/manage/tasks/index.md
Labels: create-new-project

#1342 New values.yaml reference page
  content/docs/0.18.x/reference/files/values/assets/helm-values-diff.png
  content/docs/0.18.x/reference/files/values/index.md
Labels: installation-docs, ref-page

#1378 Mo's comments
  content/docs/0.18.x/reference/files/values/index.md
Labels: ref-page

#1383 fix: Fixed broken link to automatic provisioning Helm value
  content/docs/0.17.x/api/git_provisioning/index.md
  content/docs/0.18.x/api/git_provisioning/index.md
  content/docs/0.19.x/api/git_provisioning/index.md
Labels: bug

#1371 Clarify Keptn CLI installation
  content/docs/install/_index.md
  content/docs/install/cli-install/index.md
Labels: installation-docs

#1386 Explain implicit evaluation sequence in shipyard ref
  content/docs/0.18.x/reference/files/shipyard/index.md
  content/docs/0.19.x/reference/files/shipyard/index.md
Labels: create-new-project

#1390 Marked 0.12, 0.13, 0.14, and 0.15 as unsupported and 0.19 under development
  content/docs/0.12.x/_index.md
  content/docs/0.13.x/_index.md
  content/docs/0.14.x/_index.md
  content/docs/0.15.x/_index.md
  content/docs/0.16.x/_index.md
  content/docs/0.17.x/_index.md
  content/docs/0.19.x/_index.md
Labels: documentation

#1385 Planning your project
  content/docs/0.19.x/manage/plan/index.md
Labels: create-new-project

#1404 xrefs to keptn-contrib for helm-service & jmeter-service
  content/docs/0.18.x/reference/miscellaneous/distributor/index.md
  content/docs/0.19.x/reference/files/values/index.md
Labels: chore

#1393 Add quick installation demo video and synchronize doc and video
  content/docs/0.19.x/reference/files/values/index.md
  content/docs/install/_index.md
  content/docs/install/helm-install/index.md
  content/docs/install/multi-cluster/index.md
Labels: installation-docs
